FROM python:alpine3.19
# Create a user without password
RUN adduser -D pyuser 
# Select the work directory and copy the host's directory inside it  
WORKDIR /app
COPY ./application /app
# Give permission
RUN chown -R pyuser:pyuser /app
# Use pip to install the needed packages 
RUN pip install -r requirements.txt 
# Select the default user and give the entrypoint for the container 
USER pyuser 
ENTRYPOINT ["uwsgi", "--ini", "uwsgi.ini"]