FROM python:alpine3.19
RUN useradd -ms /bin/bash pyuser
WORKDIR /app
COPY ./application /app
RUN chown pyuser:pyuser /app
RUN pip install -r requirements.txt 
USER pyuser 
ENTRYPOINT ["uwsgi", "--ini", "uwsgi.ini"]