apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: todolist
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort  

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
