version: "3"
services:
  app:
    image: localhost:5000/py_app:1.1
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db_app1
      DB_PROTOCOL: postgresql+psycopg2
    networks:
      - test-net
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db_app1
      POSTGRES_PASSWORD: password 
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test-net 
networks:
  test-net: