name: update python app
on:
  push:
    branches:
      - master
jobs:
  set_version:
    runs-on: ubuntu-latest
    outputs:
      id: set_version
      set-version: ${{ steps.set_version.outputs.version }}
    steps:   
      - name: pwd
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          ls -R
      
  
  copy_code:
    needs: set_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy the code 
        run: |
          cp -r python_project/static/ python_project/templates/ python_project/app.py python_project/requirements.txt python_project/uwsgi.ini docker_container/application/
        working-directory: ${{ github.workspace }}

  build_image:
    needs: copy_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build new image
        run: |
          cd ./docker_container 
          docker build -t py_app:latest .
          
  test_image:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test image
        run: docker run --rm py_app:${{ needs.set_version.outputs.set-version }} --name test:${{ needs.set_version.outputs.set-version }}

  login_and_push:
    needs: test_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/py_app:${{ needs.set_version.outputs.set-version }}
